apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
  labels:
    app: final-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project  
    spec:
      containers:
      - name: final-project
        image: 366865076216.dkr.ecr.us-east-1.amazonaws.com/final-project:latest    
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: FINALPROJECTTOKEN
          valueFrom:
            secretKeyRef:
              name: finalproject-secret
              key: FINALPROJECTTOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: final-project-service
spec:
  type: LoadBalancer
  selector:
    app: final-project
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000