name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}   # ensures conda environment is activated

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-update-conda: true
          channels: conda-forge,defaults

      # -------------------
      # Cache conda packages
      # -------------------
      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: ~/.conda/pkgs
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      # -------------------
      # Cache pip dependencies
      # -------------------
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-pip.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # -------------------
      # Create conda environment
      # -------------------
      - name: Create conda environment
        run: |
          # Remove env if it exists (prevents exit code 1)
          conda env remove -n atlas || echo "Environment atlas does not exist"
          # Create env from environment.yml
          conda env create -f environment.yml

      # -------------------
      # Install pip dependencies (if needed)
      # -------------------
      - name: Install pip dependencies
        run: |
          conda run -n atlas pip install -r requirements-pip.txt

      # -------------------
      # Run DVC pipeline
      # -------------------
      - name: Run DVC pipeline
        run: conda run -n atlas dvc repro
