name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: create conda environment
        run: conda create -n atlas python=3.10 -y

      - name: install conda dependencies
        run: conda install -n atlas -c conda-forge numpy=1.26.4 scipy=1.14.0 pandas=2.2.2 matplotlib=3.9.1 scikit-learn=1.5.1 -y

      - name: install pip dependencies
        run: |
          conda run -n atlas pip install -r requirements-pip.txt
          conda run -n atlas pip install dvc[all]

      - name: run pipeline
        run: conda run -n atlas dvc repro
