name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: run pipeline
        env:
          FINALPROJECTTOKEN: ${{ secrets.FINALPROJECTTOKEN }}
        run: |
          dvc repro
      - name: Run model tests
        env:
          FINALPROJECTTOKEN: ${{ secrets.FINALPROJECTTOKEN }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          FINALPROJECTTOKEN: ${{ secrets.FINALPROJECTTOKEN }}
        run: python scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        env:
          # The token DagsHub looks for
          DAGSHUB_USER_TOKEN: ${{ secrets.FINALPROJECTTOKEN }}
          # The username MLflow needs for logging
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          # The password MLflow needs (which is the DagsHub token)
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.FINALPROJECTTOKEN }}
        run: python -m unittest tests/test_flask_app.py